language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: unit2 discover && sphinx-build -nW -b html -d _build/doctrees . _build/html