language: python

services:
  - mongodb

python:
  - "2.7"

# command to install dependencies
install:
    - curl -L http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.0/wkhtmltox-linux-amd64_0.12.0-03c001d.tar.xz | xz -dkc - | tar -x
    - ln -s wkhtmltox/bin/wkhtmltopdf /usr/bin/wkhtmltopdf
    - pip install -r requirements_test.txt --use-mirrors

# command to run tests
script: make test