language: python

services:
  - mongodb

python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements_test.txt --use-mirrors"

# command to run tests
script: unit2 discover && sphinx-build -nW -b html -d _build/doctrees . _build/html