language: python

services:
  - mongodb

python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements_test.txt --use-mirrors"

# command to run tests
script: make test doc