language: python

services:
  - mongodb

python:
  - "2.7"

# command to install dependencies
install:
    - curl http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb > /tmp/wkhtmltox-0.12.1_linux-trusty-amd64.deb
    - sudo dpkg -i /tmp/wkhtmltox-0.12.1_linux-trusty-amd64.deb
    - pip install -r requirements_test.txt --use-mirrors

# command to run tests
script: make test