parameters: 
    base_url: '/'


# the webapp module can be used to store the application code
webapp:


element:
    base_url: '%base_url%'

    managers:
        fs:
            content:        '%project.root_folder%/content'
            
        mongodb:
            server:     mongodb://localhost:27017/
            database:   element
            collection:
                data:   elements

element.plugins.security:
    role_hierarchy:
        ROLE_PUBLIC:      [IS_AUTHENTICATED_ANONYMOUSLY]
        ROLE_ADMIN:       [ROLE_PUBLIC, ROLE_USER]

    providers:
        in_memory:
            users:
                - {'username': 'admin', 'password': 'admin', roles: ['ROLE_ADMIN']}

    firewalls:
        private:
            pattern:            ^/(admin|api)(.*)
            http_basic:
                provider:       element.plugins.security.provider.in_memory
                # login_path:     /admin/login
                # use_forward:    false
                # check_path:     /admin/login_check
                # failure_path:   null
            # logout:
                # path:           /admin/logout
            anonymous:          false  # allow anonymous connection

        public:
            pattern:            "^/.*"
            anonymous:          true    # allow anonymous connection

    access_control:
        - { path: ^/admin/login$,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(admin|api),        role: ROLE_ADMIN }
        - { path: ^/.*,                 role: ['IS_AUTHENTICATED_ANONYMOUSLY'] }

element.plugins.seo:
    title_pattern: "%seo.title_pattern%"
    metas:
        name:
            keywords:             python, element, cms, markdown
            description:          Python Element by Thomas Rabaix ~ A CMS based on Tornado with a bit of "ioc"
            robots:               index, follow
            viewport:             width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no

        property:
            # Facebook application settings
            #'fb:app_id':          XXXXXX
            #'fb:admins':          admin1, admin2

            # Open Graph information
            # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
            'og:site_name':       Python Element by Thomas Rabaix
            'og:description':     A CMS based on Tornado

        http-equiv:
            'Content-Type':         text/html; charset=utf-8
            #'X-Ua-Compatible':      IE=EmulateIE7

element.plugins.cache:
    cache_control:
        - { "path": "^.*\\.(txt|jpg|png|gif|xls|doc|docx)$",    "Cache-Control": ['public', 's-maxage=14212800']}
        - { "path": "^(blog|gallery).*",    "Cache-Control": ['public', 's-maxage=3600']}
        - { "path": "^.*\\.rss",            "Cache-Control": ['public', 's-maxage=3600']}
        - { "path": "^contact.*",           "Cache-Control": ['private', 'must-revalidate']}
        - { "path": "^/$",                  "Cache-Control": ['public', 's-maxage=3600']}
        
element.plugins.disqus:
    settings: {}
    account: account name

ioc.extra.tornado:
    port:               8080
    name:               ''
    #static_public_path: '/static'
    static_url_path:    ''
    #static_folder:      '%project.root_folder%/resources/static'
    template_folder:    'templates'

#ioc.extra.redis:
#    connections:
#        websocket: { db: 1 }
#    clients:
#        websocket:
#            connection: websocket

element.plugins.action:
element.plugins.blog:
element.plugins.contact:
element.plugins.errors:
element.plugins.feed:
element.plugins.media:
element.plugins.node:
element.plugins.page:
element.plugins.static:
element.plugins.ngadmin:
element.plugins.api:
#element.plugins.websocket:
element.plugins.formatter:

ioc.extra.event:
ioc.extra.stats:
ioc.extra.command:
ioc.extra.jinja2:
ioc.extra.mailer:
    host:       smtp.localhost
    port:       
    user:       
    password:   

ioc.extra.locator:
