services:
    element.command.list_node:
        class: element.command.ListTypeCommand
        arguments: 
            - '@element.node.manager'
        tags:
            command:
                - { name: 'element:list' }

    element.command.load_demo_fixtures:
        class: element.command.LoadDemoFixtureCommand
        arguments:
            - '@element.manager.mongodb'
        tags:
            command:
                - { name: 'element:demo:fixtures' }