services:
    element.handler.disqus:
        class: element.handlers.disqus.DisqusHandler
        arguments:
            - '%element.disqus.account%'
        tags:
            event.listener:
                - { name: node.comment.list, method: listener }
            
            element.handler: 
                - { name: disqus.comments }
