services:
    element.handler.action.redirect:
        class: element.handlers.action.RedirectHandler
        arguments:
            - '%element.web.base_url%'
        tags:
            element.handler: 
                - { name: action.redirect }
