services:
    element.proxy.media.medias:
        class: element.listeners.media.ProxyMediasMethod
        arguments:
            - '@element.node.manager'

    element.proxy.media.static:
        class: element.listeners.media.ProxyStaticMethod
        arguments:
            - {
                'document': [ 
                    'pdf', 'txt', 'rtf',
                    'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pttx',
                    'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb',
                    'csv', 'xml', 'zip'
                ],
                'image':    ['jpg', 'png', 'jpeg', 'gif'],
                'video':    ['avi', 'mpg', 'mpg4']
            }
            
    element.listener.media:
        class: element.listeners.media.MediaListener
        arguments:
            - '@element.proxy.media.medias'
            - '@element.proxy.media.static'
        tags:
            event.listener: 
                - { name: element.node.load.success, method: add_methods }
                - { name: element.nodes.load.success, method: add_methods }


        