services:
    element.listener.default_index:
        class: element.listeners.default.DefaultIndex
        arguments:
            - '@element.node.manager'
        tags:
            event.listener: 
                - { name: element.node.not_found, method: default_index }

                