services:
    element.listener.standardize:
        class: element.listeners.standardize.Standardize

        tags:
            event.listener: 
                - { name: element.node.load.success, method: normalize_node }
                - { name: element.nodes.load.success, method: normalize_nodes }
                - { name: element.node.render_response, method: render_response }