services:
    element.flask.blueprint:
        class: flask.Blueprint
        arguments: 
            - 'element'
            - 'element'
        kwargs:
            template_folder: '%element.template.dir%'
            static_folder:   '%element.static.dir%'
        
    element.flask.view.index:
        class: [element.views, PathView.as_view]
        arguments: 
            - 'element_path'
            - '@element.node.manager'
            - '@element.context.creator'
            - '@ioc.extra.event_dispatcher'

    element.context.creator:
        class: element.context.ContextCreator

    element.node.manager:
        class: element.node.NodeManager
        arguments: 
            - '@element.manager.default'
            - '@ioc.extra.event_dispatcher'

    element.manager.default:
        class: element.manager.fs.FsManager
        arguments:
            - '%element.data.dir%'
            - '@element.loader.chain'

    element.loader.chain:
        class: element.loaders.LoaderChain

    element.loader.yaml:
        class: element.loaders.YamlNodeLoader
        tags:
            element.loader: 
                - name: yaml

    element.loader.inline:
        class: element.loaders.InlineLoader
        tags:
            element.loader: 
                - name: inline