services:
    element.node.renderer:
        class: element.views.NodeRenderer
        arguments:
            - '@element.node.manager'
            - '@element.context.creator'
            - '@ioc.extra.event_dispatcher'
            - '@logger'

    element.tornado.view.index:
        class: element.views.PathView
        arguments: 
            - '@element.node.manager'
            - '@element.node.renderer'
            - '@ioc.extra.event_dispatcher'

    element.context.creator:
        class: element.context.ContextCreator
        arguments:
            - '@ioc.extra.event_dispatcher'

    element.node.manager:
        class: element.node.NodeManager
        arguments: 
            - '@element.manager.chain'
            - '@ioc.extra.event_dispatcher'
        kwargs:
            logger: '@logger'

    element.manager.chain:
        class: element.manager.tools.ChainManager
        arguments:
            - '' # managers references
        kwargs:
            logger: '@logger'

    element.manager.fs:
        class: element.manager.fs.FsManager
        arguments:
            - '' # data dir
            - '@element.loader.chain'
        kwargs:
            logger: '@logger'

    element.manager.mongodb:
        class: element.manager.mongo.MongoManager
        arguments:
            - '@element.manager.mongodb.client' 
            - '' # database
            - '' # data collection
        kwargs:
            logger: '@logger'
            
    element.manager.mongodb.client:
        class: pymongo.MongoClient
        arguments:
            - '' # mongodb URI server

    element.loader.chain:
        class: element.loaders.LoaderChain

    element.loader.yaml:
        class: element.loaders.YamlNodeLoader
        tags:
            element.loader: 
                - name: yaml

    element.loader.inline:
        class: element.loaders.InlineLoader
        tags:
            element.loader: 
                - name: inline
